# add comments - Mei-account2 0527
# Configuration for staging environment
#
version: 1.0
app:
  # build id to deploy. if 'version' is commented out, the application is not deployed
  maven:
    groupId: net.wasdev.wlp.sample
    artifactId: ferret
    version: "1.2"
    type: war
  services:
      arn:
    - awsEndpointService: com.amazonaws.vpce.us-east-1.vpce-svc-038584aa8a44934a3
  # Enable a public endpoint for the application. If not set, the application
  # is only available on an internal endpoint accessible to other applications
  # within a subscription.
  endpoints: public
  #endpoints: vpe
  
  # number of instances
  instances:
    # min number of instances. can be 0 for scale to 0. default to 1.
    min: 1
    
    # max number of instances. defaults to 1 if min == 0, otherwise defaults to min
    max: 4
    
  resources:
    # max cpu. memory limit is based on cpu value: 1:3 memory ratio, e.g. 1 cpu == 4 gb
    cpu: 1

  # List of environment variables that are set for the application
  env:
    - name: JVM_ARGS 
      value: "-Xms=1024m"

  # List of variables that can be referenced in the server.xml
  variables:
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
